### ISSUE TITLE
Checklist for Launch

### ISSUE THREAD

**Issue by anandology** [fossunited/mon_school#20]
## Course Contents
- [ ] Add Generating Chapter
- [ ] Add Recursion Chapter
- [ ] Update the Lists Chapter
- [ ] Restructure the Getting Started Chapter

## Videos
- [ ] Add course teaser video
- [ ] Add videos for getting started chapter

## Tasks
- [ ] Implement the new design for the livecode editor #19

## Issues
- [ ]  Sketches page is slow to load #14
- [ ]  Disable submit exercise when the user is not logged in  #10 

## To review
- [ ] signup flow

**Comment by anandology** [comment]
Other issues:
- The license should be changed to AGPL
- The color of login button is blue instead of green
