### ISSUE TITLE
Checklist for launch

### ISSUE THREAD

**Issue by anandology** [fossunited/mon_school#37]
## mon.school instance

- [x] install postfix to send email 
- [x] setup email in desk
- [x] add about page
- [x] launching blog post 

## The Joy of Programming Course

- [ ] add joy of programming course
- [ ] add video for the course
- [x] add course outline
- [x] create one batch for Navgurukul

## Sketches

- [x] add 10 sketches
- [x] 10 sketches from the students of the old batch

## LiveCode

- [ ] Add timeout to livecode execution or a cron job to delete long running container
- [ ] Add CPU and memory limits

## Tweaks
- [ ] Add a small description to Sketches page explain what are these sketches
- [ ] Add a reference guide to skectch editor
- [ ] Improve the code editor

## Style Issues
- [x] request invite email box is too small on mobile

## Bugs
- [x] Invalid email address shows the error in a popup instead of showing it above the form
- [x] Username validations
