### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by anandology** [fossunited/mon_school#77]
We need to create a score for every student to encourage them to make progress in the course and also help mentors to see how the students are performing.

## Tasks

- [ ] create a Student Score doctype with the fields email, cohort, subgroup, executions, exercises, sketches, score
- [ ] a progress page for each subgroup with score for every user 
- [ ] compute daily active users per subgroup and cohort (also weekly active users) 
- [ ] compute #executions and #exercise-submissions 

## Formula for computing score

```
bool(executions) + bool(sketches) * 5 + bool(exercises) * 4 + exercises
```

This is updated on every execution, sketch creation, new exercise submission.

## Active User

If a person has a code run or a sketch or exercise submission, he/she is considered active.

**Comment by anandology** [comment]
@nikochiko do you think it would be good to have a doctype `Course Activity` that tracks every code execution, exercise submission and creating sketches? This could be the source for `Cohort Daily User Activity` and `Student Score Activity`. What do you think?

**Comment by anandology** [comment]
This will save us from adding multiple server scripts for `Cohort Daily User Activity` and `Student Score Activity`.

**Comment by nikochiko** [comment]
Yes that would make sense. +1

**Comment by nikochiko** [comment]
Are `Code Runs` always part of a course or can it be run independently as well?

**Comment by anandology** [comment]
Code Run can happen as part of a sketch also.

**Comment by anandology** [comment]
Course Activity will track only the activity by the logged in users of a course. Activity from the guests is not captures as part of this. @nikochiko sounds alright?

**Comment by nikochiko** [comment]
Yes. That sounds good.
Another thought I was having was about a generic type of student activity, and then that could be in a course or not. We can obtain our stats using SQL queries. Something like the way GitHub uses `event`s.

**Comment by nikochiko** [comment]
A `timestamp` perhaps? But we get that automatically with Frappe.
I think we would also need information about whether this was run as part of a cohort or not. Does it make sense to have a field for that?

**Comment by anandology** [comment]
Activity is generic and and not related to a cohort. The Student Score Activity etc. will take the Cohort etc. into consideration. For example, the Student Score Activity will be created only the user is part of a cohort. 

Eventually, we'll have to move this additional computation to the task queue so that this won't block the critical path.

**Comment by anandology** [comment]
Student Activity is ready and live! @nikochiko
