### ISSUE TITLE
Missing exercises in the student progress

### ISSUE THREAD

**Issue by anandology** [fossunited/mon_school#82]
Some students of the th-2021-12 cohort have reported that they have solved some exercises, but they not showing up in the dashboard.

Looks like there are entries in `Exercise Submission`, but there are no entries for `Exercise Latest Submission`. There are some entries in `Exercise Latest Submission` which are not attached to any member. 

There is another issue as well with the students who were shifted to another subgroup. Their `Exercise Latest Submission`entries were tagged to the earlier subgroup and messing up with numbers.

## Tasks
- [x] delete all exercise latest submission entries without any member
- [x] Go ever every exercise since Dec 1, 2021 and make sure there is a Exercise Latest Submission for that student, exercise combination, if not create one
- [x] For every student, make sure that their Exercise Latest Submission has the subgroup mentioned correctly, if not correct it.

**Comment by anandology** [comment]
The first task also means deleting the student activity and student score activity records as well.

**Comment by anandology** [comment]
There are many "Exercise Latest Submission" entries with no member. That should never have happened.

```
In [44]: frappe.get_all("Exercise Latest Submission", filters={"member": ""}, fields="count(*) as count")
Out[44]: [{'count': 2419}]
```

**Comment by anandology** [comment]
Done.
