### ISSUE TITLE
Migrate all Batches to Cohort

### ISSUE THREAD

**Issue by anandology** [fossunited/mon_school#90]
We are going to delete the batches feature from School. Before we do that we need to migrate al the batches to Cohort.

## Tasks

- [ ] Create a new cohort `th-2021-05`
- [ ] Convert each batch into a subgroup
- [ ] Add each mentor of a batch as mentor of the subgroup and delete the entries in LMS Batch membership
- [ ] Move each student of a batch as a student of the subgroup
- [ ] Delete all entries from LMS Batch
- [ ] Delete all entries from LMS Batch Mentor Mapping
