### ISSUE TITLE
A way to register a server for self-hosting course

### ISSUE THREAD

**Issue by anandology** [fossunited/mon_school#91]
For Self Hosting 101 course, we want to the users to get a subdomain so that they can host things on their server. For this we need a way to attach an IP address to the hostname of the user.

# Tasks
- [x] Create Mon School Settings doctype with digitalocean_api_token field
- [x] Create a doctype "Mon School User Subdomain"
- [x] Create a web page on Mon School that will show the current IP address mapping

**Comment by anandology** [comment]
https://mon.school/account/subdomain will show the currently attached IP address and allows the user to change to something else.
